FROM pypy:3.10 as builder

ENV PYTHONUNBUFFERED=1 \
    POETRY_HOME="/usr/local" \
    POETRY_VERSION="1.8.1"

RUN apt-get update \
    && apt-get install --no-install-recommends -y curl \
    && curl -sSL https://install.python-poetry.org | python3 -

WORKDIR /app

COPY pyproject.toml poetry.lock ./

RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi

COPY . .

ENTRYPOINT ["gunicorn", "rinha.wsgi", "-b", "0:8080"]